version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule: { interval: weekly }
    groups:
      cargo-workspace: { patterns: ["*"] }
  - package-ecosystem: pub
    directory: /packaging/pub
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
