#!/usr/bin/env node
// Prints the Homebrew formula of a release, for hidane-dev/homebrew-tap (Formula/hidane.rb):
//
//   node packaging/homebrew/formula.mjs <version> <sha256sums.txt> > Formula/hidane.rb
//
// The formula installs the release archive for the machine; Homebrew unpacks it and enters its
// one directory.

import { readFileSync } from "node:fs";

const [version, sumsFile] = process.argv.slice(2);
if (!version || !sumsFile) throw new Error("usage: formula.mjs <version> <sha256sums.txt>");

const sums = new Map(
  readFileSync(sumsFile, "utf8")
    .split("\n")
    .map((line) => line.trim().split(/\s+/))
    .filter((fields) => fields.length === 2)
    .map(([sum, file]) => [file.replace(/^\*/, ""), sum])
);

function asset(target) {
  const file = `hidane-${version}-${target}.tar.gz`;
  const sum = sums.get(file);
  if (!sum) throw new Error(`${file} is not in ${sumsFile}`);
  return `      url "https://github.com/hidane-dev/hidane/releases/download/v${version}/${file}"
      sha256 "${sum}"`;
}

process.stdout.write(`# Generated by packaging/homebrew/formula.mjs in hidane-dev/hidane.
class Hidane < Formula
  desc "Firestore emulator without Java, tested against the official one"
  homepage "https://hidane.dev"
  version "${version}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
${asset("aarch64-apple-darwin")}
    end
    on_intel do
${asset("x86_64-apple-darwin")}
    end
  end

  on_linux do
    on_arm do
${asset("aarch64-unknown-linux-musl")}
    end
    on_intel do
${asset("x86_64-unknown-linux-musl")}
    end
  end

  def install
    bin.install "hidane"
    prefix.install "LICENSE-MIT", "LICENSE-APACHE", "THIRD-PARTY-LICENSES.txt"
  end

  test do
    assert_match "hidane #{version}", shell_output("#{bin}/hidane --version")
  end
end
`);
